name: Tf dependency
description: |
  This action discovers the Terraform state directories that use the specified local modules.
  A "state directory" is where you run `terraform plan` or `terraform apply`.
  It usually contains the `terraform.tfstate` file.

  For example, if you modify a Terraform local module, you can see which state directories are affected.
  With this action, you can easily identify relationships in your Terraform configurations,
  making it easier to manage changes and understand their impacts.

  ## Usage

  ```yaml
    steps:
      - name: Tf dependency
        uses: tmknom/tf-dependency-action@v0
        with:
          modules: module/foo,module/bar
  ```

inputs:
  modules:
    required: true
    description: Paths of files or directories that might be Terraform modules.
  base-dir:
    default: ${{ github.workspace }}
    required: false
    description: The base directory that contains the state directories and module directories.

outputs:
  dirs:
    value: ${{ steps.dependent.outputs.dirs }}
    description: The state directories that use the specified modules.

runs:
  using: composite

  steps:
    - name: Install tfmod
      env:
        VERSION: v0.2.2
        BASE_URL: https://github.com/tmknom/tfmod/releases/download
      run: |
        echo "::group::Install tfmod"
        set -x
        url="${BASE_URL}/${VERSION}/tfmod_Linux_x86_64.tar.gz"
        bin_path="${RUNNER_TEMP}/${GITHUB_ACTION}/bin"
        mkdir -p "${bin_path}"

        curl -sSL -o "${bin_path}/tfmod.tar.gz" "${url}"
        tar -zxvf "${bin_path}/tfmod.tar.gz" -C "${bin_path}"
        echo "${bin_path}" >> "${GITHUB_PATH}"
        echo "::endgroup::"
      shell: bash

    - name: Run tfmod download
      env:
        BASE_DIR: ${{ inputs.base-dir }}
      run: |
        echo "::group::Run tfmod download"
        set -x
        tfmod download --debug --format=text --base="${BASE_DIR}"
        echo "::endgroup::"
      shell: bash

    - name: Run tfmod dependent
      id: dependent
      env:
        BASE_DIR: ${{ inputs.base-dir }}
        MODULES: ${{ inputs.modules }}
      run: |
        echo "::group::Run tfmod dependent"
        set -x
        dirs="$(tfmod dependent --debug --format=text --base="${BASE_DIR}" --module="${MODULES}")"
        echo "dirs=${dirs}" >> "${GITHUB_OUTPUT}"
        echo "::endgroup::"
      shell: bash
