name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml", "go.mod"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/secure-checkout-action@v1
        with:
          persist-credentials: true

      - name: Setup
        run: |
          set -x
          module="testdata/terraform/module/foo/main.tf"
          mkdir -p "$(dirname "${module}")"
          cat <<EOF >"${module}"
          resource "terraform_data" "test" {
            input = "foo"
          }
          EOF

          state="testdata/terraform/env/prd/main.tf"
          mkdir -p "$(dirname "${state}")"
          cat <<EOF >"${state}"
          module "foo" {
            source = "../../module/foo"
          }
          module "security-group" {
            source  = "terraform-aws-modules/security-group/aws"
            version = "5.1.2"
          }
          EOF

      - name: Setup Terraform
        uses: tmknom/setup-terraform-action@4eaa75f79fbd732a98d5bcc2d47e7271b8a29c66 # v0.6.4

      - name: Exercise
        id: exercise
        uses: ./
        with:
          modules: "testdata/terraform/module/foo"

      - name: Verify
        env:
          DIRS: ${{ steps.exercise.outputs.dirs }}
        run: |
          set -x
          test "${DIRS}" = "testdata/terraform/env/prd"

  test-git-diff:
    name: Test git diff
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/secure-checkout-action@v1
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Git Config
        uses: tmknom/git-config-action@970621c4819d5a601bbac4a2bcf6f5f80d92a2e6 # v0.2.0

      - name: Setup
        run: |
          set -x
          module="testdata/terraform/module/foo/main.tf"
          mkdir -p "$(dirname "${module}")"
          cat <<EOF >"${module}"
          resource "terraform_data" "test" {
            input = "foo"
          }
          EOF

          state="testdata/terraform/env/prd/main.tf"
          mkdir -p "$(dirname "${state}")"
          cat <<EOF >"${state}"
          module "foo" {
            source = "../../module/foo"
          }
          module "security-group" {
            source  = "terraform-aws-modules/security-group/aws"
            version = "5.1.2"
          }
          EOF

          git switch -c "test/${GITHUB_JOB}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
          git add .
          git commit -m "test commit"

      - name: Setup Terraform
        uses: tmknom/setup-terraform-action@4eaa75f79fbd732a98d5bcc2d47e7271b8a29c66 # v0.6.4

      - name: Exercise
        id: exercise
        uses: ./

      - name: Verify
        env:
          DIRS: ${{ steps.exercise.outputs.dirs }}
        run: |
          set -x
          test "${DIRS}" = "testdata/terraform/env/prd"
