name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Setup
        run: |
          set -x
          rm -rf testdata
          module="testdata/terraform/module/foo/main.tf"
          mkdir -p "$(dirname "${module}")"
          cat <<EOF >"${module}"
          resource "terraform_data" "test" {
            input = "foo"
          }
          EOF

          state="testdata/terraform/env/prd/main.tf"
          mkdir -p "$(dirname "${state}")"
          cat <<EOF >"${state}"
          module "foo" {
            source = "../../module/foo"
          }
          module "security-group" {
            source  = "terraform-aws-modules/security-group/aws"
            version = "5.1.2"
          }
          EOF

      - name: Exercise
        id: exercise
        uses: ./
        with:
          modules: "testdata/terraform/module/foo"

      - name: Verify
        env:
          DIRS: ${{ steps.exercise.outputs.dirs }}
        run: |
          set -x
          test "${DIRS}" = "testdata/terraform/env/prd"
